site_name: UVC-Reha 


theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: indigo 
    accent: indigo
  logo: 'favicon.png'
  favicon: 'favicon.png'


nav:
- Übersicht: index.md
- Installation: installation.md
- Development: development.md


markdown_extensions:
- markdown_include.include:
    base_path: docs
