site_name: UVC-Reha 


theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: indigo 
    accent: indigo
  logo: 'favicon.ico'
  favicon: 'favicon.ico'


nav:
- Übersicht: index.md
- Installation: installation.md
- Handling: handling.md
- Development: development.md
- Views: views.md
- Forms: forms.md
- SMTP: smtp.md
- AMQP: amqp.md


markdown_extensions:
- markdown_include.include:
    base_path: docs
